# Generated by Django 3.0.8 on 2020-08-25 18:50

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bd_name', models.CharField(max_length=10, verbose_name='게시판 이름')),
                ('bd_right', models.BooleanField(default=False, null=True, verbose_name='게시판 열람 권한')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=10, verbose_name='카테고리 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_notice', models.BooleanField(default=False, null=True, verbose_name='게시물 공지여부')),
                ('post_name', models.CharField(max_length=50, verbose_name='게시물 제목')),
                ('post_modifydate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='게시물 등록(수정)일')),
                ('post_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='게시물 내용')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Board', verbose_name='게시판 이름')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='카테고리 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmt_content', models.CharField(max_length=200, verbose_name='댓글 내용')),
                ('cmt_history', models.CharField(max_length=200, verbose_name='댓글 수정 내역')),
                ('cmt_modifydate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='댓글 등록(수정)일')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='댓글 작성자')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='게시물 번호')),
                ('reply_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment', verbose_name='대댓글')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='카테고리 이름'),
        ),
    ]
