# Generated by Django 3.0.8 on 2020-08-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', '여'), ('male', '남'), ('not-specified', 'Not Specified')], max_length=50, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest_part',
            field=models.CharField(choices=[('양식', '양식'), ('일식', '일식'), ('중식', '중식'), ('한식', '한식')], max_length=50, null=True, verbose_name='관심 요리 분야'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
