# Generated by Django 3.0.8 on 2020-08-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200806_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not Specified'), ('male', '남'), ('female', '여')], max_length=50, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest_part',
            field=models.CharField(choices=[('중식', '중식'), ('양식', '양식'), ('일식', '일식'), ('한식', '한식')], max_length=50, null=True, verbose_name='관심 요리 분야'),
        ),
    ]
