# Generated by Django 3.0.8 on 2020-08-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200806_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest_part',
            field=models.CharField(choices=[('양식', '양식'), ('한식', '한식'), ('중식', '중식'), ('일식', '일식')], max_length=50, null=True, verbose_name='관심 요리 분야'),
        ),
    ]
